var html = "";

html = '   <!-- Start - Menu Sistema -->';
html += '        <div class="navbar navbar-fixed-top">';
html += '            <div class="navbar-inner ">';
html += '                <div class="container-fluid">';
html += '                    <button  class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">';
html += '                        <span class="icon-bar"></span>';
html += '                        <span class="icon-bar"></span>';
html += '                        <span class="icon-bar"></span>';
html += '                    </button>';
html += '                   <a href="Home">';
html += '                    <img width="35" src="resources/images/2000px-BrasaoSorocaba.png" class="logo-thumb">';
html += '                    <span id="logo" class="brand">Museu Sorocaba</span>';
html += '                       </a>';
html += '                    <div class="nav-collapse collapse ">';
html += '                        <!-- Start - Links Menu Sistema -->';
html += '                        <ul class="nav navbar-nav">';
html += '                            <li class="dropdown">';
html += '                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Objetos<b class="caret"></b></a>';
html += '                                <ul class="dropdown-menu">';
html += '                                    <li  role="presentation" class="dropdown-header">Cadastros</li>';
html += '                                    <li><a href="object">Objetos</a></li>'                                    
html += '                                </ul>';
html += '                            </li>';
html += '                            <li class="dropdown">';
html += '                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Museu<b class="caret"></b></a>';
html += '                                <ul class="dropdown-menu">';
html += '                                    <li  role="presentation" class="dropdown-header">Cadastros</li>';
html += '                                    <li><a href="museum">Museu</a></li>';
html += '                                </ul>';
html += '                            </li>';
html += '                            <li class="dropdown">';
html += '                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Cenário<b class="caret"></b></a>';
html += '                                <ul class="dropdown-menu">';
html += '                                    <li  role="presentation" class="dropdown-header">Cadastros</li>';
html += '                                    <li><a href="scenario">Cenário</a></li>';                                    
html += '                                    <li><a href="theme">Título</a></li>';
html += '                                </ul>';
html += '                            </li>';
html += '                        <!-- End - Links Menu Sistema -->  ';
html += '                        <!-- Start - User Info -->';
html += '                        <ul class="nav pull-right">';
html += '                            <li class="dropdown">';                             
html += '                               <ul class="dropdown-menu">';
html += '                                  <li><a role="menuitem" tabindex="-1" href="Login"><i class="icon-remove"></i> Logoff</a></li>';
html += '                             </ul>';
html += '                           </li>';
html += '                        </ul>';
html += '                        <!-- End - User Info -->';
html += '                   </div>';
html += '               </div>';
html += '          </div>';
html += '        </div>';
html += '      <!-- End - Menu Sistema -->';



html = '';
html += '<div class="navbar navbar-default navbar-static-top" role="navigation">';
html += '    <div class="container">';
html += '        <div class="navbar-header">';
html += '            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">';
html += '                <span class="sr-only">Toggle navigation</span>';
html += '                <span class="icon-bar"></span>';
html += '                <span class="icon-bar"></span>';
html += '                <span class="icon-bar"></span>';
html += '            </button>';
html += '            <a class="gdata-nav-link navbar-brand" href="javascript:void();" data-function="gdata-info">';
html += '                Facens';
html += '            </a>';
html += '        </div>';
html += '        <div class="collapse navbar-collapse">';
html += '            <ul class="nav navbar-nav gdata-navbar">';
html += '                <li id="nav-museum">';
html += '                    <a href="museum" data-toggle="collapse" data-target=".navbar-collapse">';
html += '                        <span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;Museu';
html += '                    </a>';
html += '                </li>';
html += '                <li id="nav-scenario" class="dropdown">';
html += '                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-film"></span>&nbsp;&nbsp;Cenário<span class="caret"></span></a>';
html += '                    <ul class="dropdown-menu" role="menu">';
html += '                        <li><a href="scenario">Cenário</a></li>';
html += '                        <li><a href="theme">Título</a></li>';
html += '                        <li><a href="present">Presente/Passado</a></li>';
html += '                    </ul>';
html += '                </li>';
html += '                <li id="nav-object">';
html += '                    <a href="object" data-toggle="collapse" data-target=".navbar-collapse">';
html += '                        <span class="glyphicon glyphicon-bishop"></span>&nbsp;&nbsp;Objeto';
html += '                    </a>';
html += '                </li>';
html += '            </ul>';
html += '        </div>';
html += '    </div>';
html += '</div>';
 
document.write(html);

var pag = (window.location.pathname).split("/").pop();
document.getElementById("nav-" + pag).className = document.getElementById("nav-" + pag).className + " active";
